/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-12-31 12:35:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;

public final class Developers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/E:/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Web/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098685890000L));
    _jspx_dependants.put("jar:file:/E:/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Web/WEB-INF/lib/standard.jar!/META-INF/sql.tld", Long.valueOf(1098685890000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1513609077695L));
    _jspx_dependants.put("jar:file:/E:/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Web/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098685890000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\"; content=\"text/html\"; charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/reset.css\" media=\"screen\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/Editer.css\" media=\"screen\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/W3.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"Images/brainstorming.png\"/>\r\n");
      out.write("\r\n");
      out.write("    <title>Editer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     <!--BEGIN: Logo Trang SPKT-->\r\n");
      out.write("    <header>\r\n");
      out.write("        <div id=\"Logo\">\r\n");
      out.write("          <figure>\r\n");
      out.write("              <img src=\"Images/SPKT.jpg\" alt=\"logo\">\r\n");
      out.write("          </figure>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!--END: Logo Trang SPKT-->\r\n");
      out.write("    <section class=\"container\">\r\n");
      out.write("        <h1 class=\"text\">Trắc Nghiệm Online - Editer</h1>\r\n");
      out.write("        <div class=\"menu\">\r\n");
      out.write("            <a href=\"TrangChu.html\" class=\"btn\">Trang Chủ</a>\r\n");
      out.write("            <a href=\"DangNhap.html\" class=\"btn\">Đăng Nhập</a>\r\n");
      out.write("            <a href=\"#\" class=\"btn\">Đăng Ký</a>\r\n");
      out.write("            <a href=\"#\" class=\"btn\">Hỗ Trợ</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"sidebar\">\r\n");
      out.write("        <div class=\"w3-sidebar w3-bar-block w3-animate-left\" style=\"display:none;z-index:5\" id=\"mySidebar\">\r\n");
      out.write("            <button class=\"w3-bar-item w3-button w3-large w3-blue w3-hover-orange\" onclick=\"w3_close()\">Đóng &times;</button>\r\n");
      out.write("            <a href=\"#\" class=\"w3-bar-item w3-button w3-text-blue w3-hover-orange\">Trang Chủ</a>\r\n");
      out.write("            <a href=\"#\" class=\"w3-bar-item w3-button w3-text-blue w3-hover-orange\">Đăng Nhập</a>\r\n");
      out.write("            <a href=\"#\" class=\"w3-bar-item w3-button w3-text-blue w3-hover-orange\">Đăng Ký</a>\r\n");
      out.write("            <a href=\"#\" class=\"w3-bar-item w3-button w3-text-blue w3-hover-orange\">Hổ Trợ</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w3-overlay w3-animate-opacity\" onclick=\"w3_close()\" style=\"cursor:pointer\" id=\"myOverlay\"></div>\r\n");
      out.write("        <div><button class=\"w3-button w3-xxlarge \" onclick=\"w3_open()\">&#9776;</button></div>\r\n");
      out.write("        <div class=\"tieude\"><p>Trắc Nghiệm Online</p></div>\r\n");
      out.write("        <script>\r\n");
      out.write("            function w3_open() {\r\n");
      out.write("                document.getElementById(\"mySidebar\").style.display = \"block\";\r\n");
      out.write("                document.getElementById(\"myOverlay\").style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("            function w3_close() {\r\n");
      out.write("                document.getElementById(\"mySidebar\").style.display = \"none\";\r\n");
      out.write("                document.getElementById(\"myOverlay\").style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"gioithieu\">\r\n");
      out.write("        <!--BEGIN: Tiêu đề editer-->\r\n");
      out.write("        <div class=\"w3-container w3-teal GioiThieu\">\r\n");
      out.write("            <img src=\"Images/student.png\" alt=\"editer\">\r\n");
      out.write("            <p>Huỳnh Minh Chiến</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--END: Tiêu đề editer-->\r\n");
      out.write("        <div class=\"w3-container w3-center MinhChien\">\r\n");
      out.write("            <h2 class=\"profile-text\" style=\"text-align:center\">Editer Profile Card</h2>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"Images/Chien.jpg\" alt=\"Chien\" style=\"width:100%\">\r\n");
      out.write("                <h2 class=\"pro-ten\">Huỳnh Minh Chiến</h2>\r\n");
      out.write("                <p class=\"title\">Quản trị viên</p>\r\n");
      out.write("                <p>Đại học Sư phạm kỹ thuật TP.Hồ Chí Minh</p>\r\n");
      out.write("                <div style=\"margin: 24px 0;\"></div>\r\n");
      out.write("                <p><button class=\"btnCont\">Contact</button></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w3-container resume chien\">\r\n");
      out.write("            <p class=\"profile\"><img src=\"Images/proflie.png\" alt=\"lylich\" style=\"margin-right: 5px;\">Giới Thiệu</p>\r\n");
      out.write("            <div class=\"lylich\">\r\n");
      out.write("                <p><b>Họ và tên:</b> Huỳnh Minh Chiến</p>\r\n");
      out.write("                <p><b>Giới tính:</b> Nam</p>\r\n");
      out.write("                <p><b>Mã số sinh viên:</b> 15110166</p>\r\n");
      out.write("                <p><b>Lớp:</b> 151101A</p>\r\n");
      out.write("                <p><b>Khoa:</b> Công Nghệ Thông Tin</p>\r\n");
      out.write("                <p><b>Công việc:</b> Quản trị viên</p>\r\n");
      out.write("                <p  class=\"play\"><b>Mail sinh viên:</b> 15110166@student.hcmute.edu.vn</p>\r\n");
      out.write("                <p  class=\"play\"><b>Số điện thoại:</b> 01692564970</p>\r\n");
      out.write("                <p  class=\"play\"><b>Quê quán:</b> Tiền Giang</p>\r\n");
      out.write("                <p  class=\"play\"><b>Dân tộc:</b> Kinh</p>\r\n");
      out.write("                <p  class=\"play\"><b>Tôn giáo:</b> Không</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <marquee onmouseover=\"this.stop()\" onmouseout=\"this.start()\"  id=\"ten\">Phá bỏ mọi giới hạn - Ta bất tử</marquee>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"gioithieu Kha\">\r\n");
      out.write("        <!--BEGIN: Tiêu đề editer-->\r\n");
      out.write("        <div class=\"w3-container w3-teal GioiThieu\">\r\n");
      out.write("            <img src=\"Images/student.png\" alt=\"editer\">\r\n");
      out.write("            <p>Lê Hoàng Kha</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--END: Tiêu đề editer-->\r\n");
      out.write("        <div class=\"w3-container w3-center MinhChien\">\r\n");
      out.write("            <h2  class=\"profile-text\" style=\"text-align:center\">Editer Profile Card</h2>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"Images/Kha.jpg\" alt=\"Kha\" style=\"width:100%\">\r\n");
      out.write("                <h2 class=\"pro-ten\">Lê Hoàng Kha</h2>\r\n");
      out.write("                <p class=\"title\">Quản trị viên</p>\r\n");
      out.write("                <p>Đại học Sư phạm kỹ thuật TP.Hồ Chí Minh</p>\r\n");
      out.write("                <div style=\"margin: 24px 0;\"></div>\r\n");
      out.write("                <p><button class=\"btnCont\">Contact</button></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w3-container resume chien\">\r\n");
      out.write("            <p class=\"profile\"><img src=\"Images/proflie.png\" alt=\"lylich\" style=\"margin-right: 5px;\">Giới Thiệu</p>\r\n");
      out.write("            <div class=\"lylich\">\r\n");
      out.write("                <p><b>Họ và tên:</b> Lê Hoàng Kha</p>\r\n");
      out.write("                <p><b>Giới tính:</b> Nam</p>\r\n");
      out.write("                <p><b>Mã số sinh viên:</b> 15110227</p>\r\n");
      out.write("                <p><b>Lớp:</b> 151101A</p>\r\n");
      out.write("                <p><b>Khoa:</b> Công Nghệ Thông Tin</p>\r\n");
      out.write("                <p><b>Công việc:</b> Quản trị viên</p>\r\n");
      out.write("                <p class=\"play\"><b>Mail sinh viên:</b> 15110227@student.hcmute.edu.vn</p>\r\n");
      out.write("                <p class=\"play\"><b>Số điện thoại:</b> 0932687444</p>\r\n");
      out.write("                <p class=\"play\"><b>Quê quán:</b> Long An</p>\r\n");
      out.write("                <p class=\"play\"><b>Dân tộc:</b> Kinh</p>\r\n");
      out.write("                <p class=\"play\"><b>Tôn giáo:</b> Không</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <marquee onmouseover=\"this.stop()\" onmouseout=\"this.start()\"  id=\"ten\">Sống đơn giản - Ăn thật nhiều</marquee>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"gioithieu Chuan\">\r\n");
      out.write("        <!--BEGIN: Tiêu đề editer-->\r\n");
      out.write("        <div class=\"w3-container w3-teal GioiThieu\">\r\n");
      out.write("            <img src=\"Images/student.png\" alt=\"editer\">\r\n");
      out.write("            <p class=\"nameChuan\">Nguyễn Tô Doanh Chuẩn</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--END: Tiêu đề editer-->\r\n");
      out.write("        <div class=\"w3-container w3-center MinhChien\">\r\n");
      out.write("            <h2  class=\"profile-text\" style=\"text-align:center\">Editer Profile Card</h2>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"Images/Chien.jpg\" alt=\"Chuan\" style=\"width:100%\">\r\n");
      out.write("                <h3 class=\"pro-ten\">Nguyễn Tô Doanh Chuẩn</h3>\r\n");
      out.write("                <p class=\"title\">Quản trị viên</p>\r\n");
      out.write("                <p>Đại học Sư phạm kỹ thuật TP.Hồ Chí Minh</p>\r\n");
      out.write("                <div style=\"margin: 24px 0;\"></div>\r\n");
      out.write("                <p><button class=\"btnCont\">Contact</button></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w3-container resume chien\">\r\n");
      out.write("            <p class=\"profile\"><img src=\"Images/proflie.png\" alt=\"lylich\" style=\"margin-right: 5px;\">Giới Thiệu</p>\r\n");
      out.write("            <div class=\"lylich\">\r\n");
      out.write("                <p><b>Họ và tên:</b> Nguyễn Tô Doanh Chuẩn</p>\r\n");
      out.write("                <p><b>Giới tính:</b> Nam</p>\r\n");
      out.write("                <p><b>Mã số sinh viên:</b> 15110168</p>\r\n");
      out.write("                <p><b>Lớp:</b> 151101D</p>\r\n");
      out.write("                <p><b>Khoa:</b> Công Nghệ Thông Tin</p>\r\n");
      out.write("                <p><b>Công việc:</b> Quản trị viên</p>\r\n");
      out.write("                <p class=\"play\"><b>Mail sinh viên:</b> 15110168@student.hcmute.edu.vn</p>\r\n");
      out.write("                <p class=\"play\"><b>Số điện thoại:</b> 01659409220</p>\r\n");
      out.write("                <p class=\"play\"><b>Quê quán:</b> TP.Hồ Chí Minh</p>\r\n");
      out.write("                <p class=\"play\"><b>Dân tộc:</b> Kinh</p>\r\n");
      out.write("                <p class=\"play\"><b>Tôn giáo:</b> Không</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <marquee onmouseover=\"this.stop()\" onmouseout=\"this.start()\"  id=\"ten\"></marquee>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("     <!--BEGIN: Chân trang-->\r\n");
      out.write("    <footer class=\"foot\">\r\n");
      out.write("        <section id=\"page_owner_info\">\r\n");
      out.write("            <div class=\"wrapper\">\r\n");
      out.write("                <!-- Begin: Copyright -->\r\n");
      out.write("                <div class=\"copyright\">© Copyright 2017 by <a\r\n");
      out.write("                    href=\"#\">Example</a>. Chiến-Kha-Chuấn\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End: Copyright -->\r\n");
      out.write("                <!-- Begin: Social network items <--></-->\r\n");
      out.write("                <div class=\"social\">\r\n");
      out.write("                    <a href=\"javascript:void(0)\">\r\n");
      out.write("                        <img src=\"Images/icon6.png\" alt=\"Some alt text\" width=\"25\"/>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"javascript:void(0)\">\r\n");
      out.write("                        <img src=\"Images/icon7.png\" alt=\"Some alt text\" width=\"25\"/>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"javascript:void(0)\">\r\n");
      out.write("                        <img src=\"Images/icon8.png\" alt=\"Some alt text\" width=\"25\"/>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"javascript:void(0)\">\r\n");
      out.write("                        <img src=\"Images/icon9.png\" alt=\"Some alt text\" width=\"25\"/>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"javascript:void(0)\">\r\n");
      out.write("                        <img src=\"Images/icon10.png\" alt=\"Some alt text\" width=\"25\"/>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End: Social network items -->            \r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!--END: Chân trang-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
